name: jarvis_core
description: MAYA OMEGA modular, consent-aware futuristic AI assistant.
publish_to: "none"
version: 9.6.0+360
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  camera: ^0.11.0+2
  flutter_tts: ^4.2.3
  http: ^1.2.0
  crypto: ^3.0.6
  path_provider: ^2.1.2
  path: ^1.9.0
  sqflite: ^2.3.3+1
  permission_handler: ^11.3.1
  flutter_overlay_window: ^0.4.5
  screen_brightness: ^1.0.1
  torch_light: ^1.1.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  intl: ^0.19.0
  record: any
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^7.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/plans/
