allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects { subproject ->
    if (subproject.name == 'camera_android_camerax') {
        subproject.plugins.withId('com.android.library') {
            subproject.android.lint.disable += 'MemberExtensionConflict'
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
